### PR TITLE
Fixed convertPlistToJson crashing when trying to parse data from stream

### PR DESCRIPTION
**Pull request by spiralx**
This is due to the fact that it was using `plist.parseFileSync` to parse the data incoming from the stream, but that data is actually just text. So this was crashing

``` js
fs.createReadStream('test.plist', { encoding='utf-8' })
  .pipe(converter({
    from: 'plist',
    to: 'json'
  })
  .pipe(fs.createWriteStream('test.json', { encoding='utf-8' });
```

which is basically the example given in the README.

I changed it to use `plist.parseStringSync` instead, which works fine.

James

### CODE REVIEW

**Comment by doowb** [comment]
Thanks. I think I missed that when porting this over grunt-convert and making the switch from files to strings/buffers/streams.

**Comment by jonschlinkert** [comment]
Great! thanks for doing this. we should get some tests up for plist as well.

**Comment by spiralx** [comment]
The only other issue I did note was that when converting from JSON to PList strings aren't escaped with `&lt;`, `&gt;` and `&amp;`, but the actual conversion happens within the `xmlbuilder` module you include I think, so I didn't change it. It does mean that the output isn't a valid XML document though, I'll raise an issue.

All of this from having converted my `package.json` to a PList, then overwriting it with a blank file...

**Comment by jonschlinkert** [comment]
since pList doesn't get as much love as other formats, it's good to have this feedback. thanks  @spiralx

**Pull request merged**
